version: "3.9"

services:
  backend:
    build:
      context: ./backend/ApiRunner
    ports:
      - "5088:8080"  # internal port stays 80 (ASP.NET default)
    environment:
      - EnableSwagger=true

  frontend:
    build:
      context: ./ui
    ports:
      - "3000:80"
    depends_on:
      - backend
  
