# Nixpacks configuration for .NET 9 backend deployment on Kinsta

[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.install]
cmds = ["cd ApiRunner && dotnet restore"]

[phases.build]
cmds = ["cd ApiRunner && dotnet publish -c Release -o /app/out"]

[start]
cmd = "dotnet /app/out/ApiRunner.dll"
